#!/bin/sh
while read file
do
	fullpath="$(pwd)/$file"
        case "$1" in
        "C-d")
                mv "$file" ~/.trash ;;
        "C-r")
                convert -rotate 90 "$file" "$file" ;;
        "C-c")
                echo -n "$file" | xclip -selection clipboard ;;
        "C-w")
		cp "$file" ~/.dotfiles/feh/wallpaper.jpg
		feh --bg-scale /home/jonathan/.dotfiles/feh/wallpaper.jpg ;;
        esac
done

