#!/bin/sh
while read file
do
	fullpath="$(pwd)/$file"
        case "$1" in
        "C-d")
                mv "$file" ~/.trash ;;
        "C-r")
                convert -rotate 90 "$file" "$file" ;;
        "C-c")
                echo -n "$file" | xclip -selection clipboard ;;
        "C-w")
				cp "$file" ~/.config/wallpaper/wallpaper.jpg
				feh --bg-scale /home/jonathan/.config/wallpaper.jpg
				wal -c
				wal -i ~/.dotfiles/feh/wallpaper.jpg
				sudo /home/jonathan/Documents/scripts/change_theme.sh
				xdotool key super+shift+q
				/home/jonathan/Documents/scripts/restartdwmblocks.sh
				notify-send "done setting wallpaper" ;;
        esac
done

