#!/bin/bash

exec &> /dev/null

while read arg; do
	# first try matching by filename or pathname
	case "${arg,,}" in
		w\ *)
			target=$(echo "$arg"|cut -d ' ' -f 3-)
			wmctrl -a "$target"
			;;
		http*)
			$BROWSER "$arg" &
			;;
		[^/]*) # doesn't start with '/'
			sh -c "$arg"
			;;
		*.txt)
			$TERMINAL $EDITOR "$arg" &
			;;
		*.pdf | *.epub)
			zathura "$arg" &
			;;
		*.mp3)
			if ! pgrep cmus > /dev/null ; then
				$TERMINAL -e cmus &
			fi
			sleep 0.1
			cmus-remote -f "$arg"
			#$TERMINAL mpg123 -opulse "$arg" &
			;;
		*.od[tsp]|*.doc|*.docx|*.ppt|*.pptx|*.xls|*.xlsx)
			libreoffice "$arg" &
			;;
		*)
			# then try matching by mimetype
			mimetype=$(file -Lb --mime-type "$arg")
			case "$mimetype" in
				text/html)
					$BROWSER "$arg" &
					;;
				text/* | inode/x-empty | message/rfc822)
					$TERMINAL -e $EDITOR "$arg" -c ":cd %:p:h"
					;;
				inode/directory)
					cd "$arg"
					$TERMINAL &
					cd -
					#xdotool key super+6
					#$TERMINAL -e ranger "$arg" 
					;;
				image/*)
					sxiv "$arg" &
					;;
				*)
					exit 1
					;;
			esac
			;;
	esac
done
